### ISSUE TITLE
Display logic does not appear to work inside a widget

### ISSUE THREAD

**Issue by MattyBalaam** [unclecheese/silverstripe-display-logic#10]
Tested in SS 3.1Beta

If I include these lines in a widget Display Logic does not appear to work:

```
        $fields->merge(
            new FieldList(
        CheckboxField::create("ThoughtLinkBoo", _t('ThoughtWidget.ThoughtLinkBoo', "Would you like to define which page is shown and linked to?")),
        $thoughtLink = DropdownField::create("ThoughtLinkID", _t('ThoughtWidget.ThoughtLinkID', "Select a page to to"), SiteTree::get()->map())
            )
        );

        $thoughtLink->displayIf("ThoughtLinkBoo")->isChecked();
```

But if I make a CheckboxField for ThoughtLinkBoo in the page class the widget is used on, this will then trigger the showing of $thoughtLink

**Comment by michalkleiner** [comment]
Closing this issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5

If your problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using.
