### ISSUE TITLE
Fields never showing (after update to SS3.7.1 + DL 1.6.0)

### ISSUE THREAD

**Issue by micschk** [unclecheese/silverstripe-display-logic#102]
I have run a composer update and updated CMS & FW to 3.7.1, and display logic to 1.6.0.
Now for some reason, any field which has display logic applied to it via displayIf() never seems to display (stays hidden).
Used to work fine on this project, now somehow I cannot seem to get anything to work.
Tried 1.5.0 & 1.5.1 as well as wrapping in DisplayLogicWrapper, same result (nothing displaying).

Anyone else ran into this issue, or anyone else has a clue of what could be causing this?

**Comment by bummzack** [comment]
Most likely this: https://github.com/unclecheese/silverstripe-display-logic/issues/101

**Comment by nglasl** [comment]
I'm using 1.7 as mentioned in that issue, however I'm encountering the same thing as described above. Anyone else in the same boat?

**Comment by nglasl** [comment]
Okay I found the issue, the following line changed to include `.getFormField()` when going from `1.2.2` to `1.7`. If I remove it, everything goes back to normal. I'm not convinced this is a solution, so would be keen to hear others thoughts?

https://github.com/unclecheese/silverstripe-display-logic/blob/1/javascript/display_logic.js#L170

**Comment by michalkleiner** [comment]
Closing this issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5.

If the problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using.
