### ISSUE TITLE
(minor) license: BSD-3 or GPL?

### ISSUE THREAD

**Issue by micschk** [unclecheese/silverstripe-display-logic#103]
The composer file says the license is BSD-3 but LICENSE.md contains a GPLv2 license (SilverStripe uses BSD-3 because this allows 'closed source' derivative work).

> We've chosen the BSD license because it's the best possible license for our customers. For example, some of our larger customers are developing unique and novel solutions on top of SilverStripe and are integrating SilverStripe deep into their product offerings. Under a more restrictive license (such as the GPL), they'd be obligated to publish all their custom code if they want to distribute their product. But this would mean giving away their competitive advantage, which they may not want to do.

**Comment by JZubero** [comment]
@micschk Version 2.0.3 is now under BSD-3 :ok_hand:
