### ISSUE TITLE
Catchable fatal error: Argument 1 passed to DisplayLogicCriteria::addCriterion() must be an instance of DisplayLogicCriterion, instance of DisplayLogicCriteria given, called in C:\wamp\www\display-logic\code\DisplayLogicCriteria.php on line 190 and define

### ISSUE THREAD

**Issue by Josua2012** [unclecheese/silverstripe-display-logic#11]
This code, similar to your example, does not work with the latest version of SilverStripe 3.1 (github):

```
 $textColor->displayIf("typebackground")->isEqualTo('standard')
        ->orIf()
        ->group()
            ->orIf("typebackground")->isEqualTo('header')
            ->orIf("typebackground")->isEqualTo('imageres')
        ->end();
```

Catchable fatal error: Argument 1 passed to DisplayLogicCriteria::addCriterion() must be an instance of DisplayLogicCriterion, instance of DisplayLogicCriteria given, called in C:\wamp\www\display-logic\code\DisplayLogicCriteria.php on line 190 and defined in C:\wamp\www\display-logic\code\DisplayLogicCriteria.php on line 147

Thanks,
Regards,
Jose A.

**Comment by michalkleiner** [comment]
Closing this issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5

If your problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using.
