### ISSUE TITLE
addFieldsToTab with the 3rd parameter will cause fields not to show

### ISSUE THREAD

**Issue by leochenftw** [unclecheese/silverstripe-display-logic#111]
`private static $db = [
        'UnitWeight' => 'Decimal'
];`

try this

`$fields->addFieldsToTab(
                        'Root.ProductDetails',
                        Wrapper::create(TextField::create('UnitWeight')->displayIf('hasVariants')->isNotChecked()->end()
                    );`

and then in the subclass's getCMSFields:
`
$fields->addFieldsToTab(
            'Root.ProductDetails',
            [
                TextField::create('Width'),
                TextField::create('Height'),
                TextField::create('Depth'),
            ],
            'UnitWeight'
 );
`

Then all these fields are not showing when check the box of 'hasVariants'

**Comment by michalkleiner** [comment]
This is because the name of the field that the Wrapper creates is not `UnitWeight`, so the fields in your subclass are actually inside the wrapper and get hidden at the same time. You need to add them after the wrapper, not after the field inside the wrapper.
