### ISSUE TITLE
IE11/Firefox: display logic doesn't work on unsupported fields (e.g. DateField, Datetimefield).

### ISSUE THREAD

**Issue by GuySartorelli** [unclecheese/silverstripe-display-logic#119]
In IE11, display logic doesn't operate on DateFields even if using a Wrapper. It seems to work fine on other fields e.g. TimeFields.
**Observed behaviour:** Using `hideIf` or `displayUnless` results in the field _always_ displaying. Using `hideUnless` or `displayIf` results in the field always being hidden.
It works correctly in Firefox and Chrome - the described behaviour is specific to IE11.

Datetimefields fail for the same reason in Firefox

`setHTML5(false)` on the DateField does allow display-logic to work correctly, but this means that the datepicker doesn't display in browsers which support it.

Display-logic version: 2.0.3

**Comment by GuySartorelli** [comment]
Looks like this might be caused by [adding a hidden field](https://github.com/silverstripe/silverstripe-admin/blob/553cffe5ddf5bfbf7ebbe0dd03e3afd423b4f6bf/client/src/legacy/DatetimeField.js#L22-L29) with the field name set as the hidden field's name attribute for browsers that don't handle datetime-local input fields.

Because display logic [prioritises field names over IDs](https://github.com/unclecheese/silverstripe-display-logic/blob/845ab12189439422b6dcd1becd20c9d5a94eb558/client/src/components/display_logic.js#L68-L72) the hidden field is picked up as _the_ field, but it doesn't have the [attributes needed](https://github.com/unclecheese/silverstripe-display-logic/blob/845ab12189439422b6dcd1becd20c9d5a94eb558/client/src/components/display_logic.js#L169-L173) to set it up correctly.

@unclecheese Do you know why name is prioritised over ID? Prioritising the field ID would resolve this particular issue.

**Comment by unclecheese** [comment]
I think it's because IDs are unpredictable. The form templates are under no contract to keep them the same across major releases, and we saw display logic completely fall on its face in a minor release due to changes in the naming strategy. Plus, they can be user defined. 

IIRC, the way the display logic javascript works is by predicting the naming and positioning of specific elements given a single form input, so my guess is that it's all related to that.

**Comment by GuySartorelli** [comment]
Right, that makes sense.
In that case a solution for this would probably have to include logic specific to the datetime field - it could even have the same `if (modernizr.inputtypes['datetime-local'])` check [used in silverstripe-admin](https://github.com/silverstripe/silverstripe-admin/blob/553cffe5ddf5bfbf7ebbe0dd03e3afd423b4f6bf/client/src/legacy/DatetimeField.js#L12) since this is only a problem when that check evaluates false.

My proposal is to replace [the field selection code](https://github.com/unclecheese/silverstripe-display-logic/blob/845ab12189439422b6dcd1becd20c9d5a94eb558/client/src/components/display_logic.js#L68-L72) with the following:

```javascript
const idField = this.find(`#${this.getFormID()}_${name}`);
const nameField = this.find(`[name=${name}]`);

if (!nameField.length || idField.attr('type') === 'datetime-local' && !modernizr.inputtypes['datetime-local']) {
    return idField;
}

return nameField;
```

This retains the previous logic, except in the case where the field is a datetime-local input and that input type is not supported by the browser. In that case, the current logic selects the hidden input field (which doesn't have the necessary data attributes). The proposed logic will instead correctly select the datetime-local input field.

If that looks okay to you, I'll submit a pull request.

**Comment by GuySartorelli** [comment]
Also FYI it seems this also affects Firefox. I've edited the issue title to reflect that.

**Comment by GuySartorelli** [comment]
Oops! It seems I forgot this was originally for date fields specifically - updated the description.
If you think the above is okay for datetime, I'll make the necessary adjustments for date and time fields individually as well when making the pull request.

**Comment by GuySartorelli** [comment]
I don't really have the time right now unfortunately. If it was literally just the snippet in my comment above I'd go for it, but it sounds like something needs to happen for date fields too and I don't have time to check what is needed for those and implement it.

I'll keep this issue in my bookmarks though and when I free up (some time after April when CMS 5 is launched) if nobody else has taken a stab at this I'll come back to it.

**Comment by GuySartorelli** [comment]
@michalkleiner I don't have access to IE anymore but given that's no longer supported in the CMS I think we can ignore it.
In Firefox, datetime-local input fields are now supported, and display-logic works fine with them provided you use a `Wrapper`.

Closing this as no longer a problem.
