### ISSUE TITLE
Getting display_logic working with other fields

### ISSUE THREAD

**Issue by Leapfrognz** [unclecheese/silverstripe-display-logic#12]
Could include a wrapper form field to wrap fields that aren compatible with DL. Simply extend CompositeField:

```
<?php
class DisplayLogicWrapper extends CompositeField {
}
```

and a template:

```
<$Tag class="field WrapperField $extraClass <% if ColumnCount %>multicolumn<% end_if %>" <% if DisplayLogic %>data-display-logic-masters="$DisplayLogicMasters"<% end_if %>>

    <% if $Tag == 'fieldset' && $Legend %>
        <legend>$Legend</legend>
    <% end_if %>

    <% loop FieldList %>
        <% if ColumnCount %>
            <div class="column-{$ColumnCount} $FirstLast">
                $FieldHolder
            </div>
        <% else %>
            $FieldHolder
        <% end_if %>
    <% end_loop %>

    <% if Description %><span class="description">$Description</span><% end_if %>

    <% if DisplayLogic %>
        <div class="display-logic-eval">$DisplayLogic</div>
    <% end_if %>

</$Tag>

```

Fairly simple. Just copied code from CompositeField and added your special tags.
Works for me when wrapping a Gridfield anyway.

**Comment by evilfer** [comment]
Hi, I'm not able to make display-logic work with LiteralField, UploadField or TreeDropdownField. I'm using DisplayLogicWrapper. By the way, I cannot find that template in the repository, should I create it? Where? I'm using SilverStripe 3.1.9.

There are more details of my case in this question: http://stackoverflow.com/questions/27965104/silverstripe-and-display-logic-fails-with-certain-field-types

**Comment by michalkleiner** [comment]
Closing this issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5

If your problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using.
