### ISSUE TITLE
DisplayIf with CheckboxSetField value

### ISSUE THREAD

**Issue by polycode-nz** [unclecheese/silverstripe-display-logic#133]
Is it possible to use the value of specific checkboxes in a CheckboxSetField to show other fields?

I've tried using the `Wrapper` and I've tried `isChecked()` and `isEqualTo()`.

`isEqualTo()` is close but it only works for the last one checked. I'm looking for all the checked check boxes to display a corresponding HTML editor field.

**Comment by michalkleiner** [comment]
Hello! Thank you for raising the issue and apologies it hasn't been responded to earlier.

Yes, it should be possible to target specific checkboxset values. Can you provide a complete code snippet replicating your situation? Make sure you're on an up-to-date version of Silverstripe CMS (4.12) and Display Logic 2.0.5.

**Comment by polycode-nz** [comment]
Hi @michalkleiner sorry too much time has passed for me to provide anything useful.

**Comment by michalkleiner** [comment]
No worries, thanks for getting back to me. I'll close the issue now but if you still have a problem with the module, feel free to open a new one. 

All the best!
