### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by GuySartorelli** [unclecheese/silverstripe-display-logic#135]
As per title. If this is not still being maintained, it might be worth checking if anyone wants to be added as a maintainer. This is still a very useful module and seems to be widely used, but the issues are starting to pile up.

**Comment by christopherdarling** [comment]
bump @unclecheese

**Comment by xini** [comment]
bump @unclecheese

**Comment by michalkleiner** [comment]
@GuySartorelli should the core team take on this, move it to the `silverstripe` namespace? Or is there one by silverstripe that would not make it an officially supported module but still "looked after"-ish?
Otherwise, I'd be ok taking it on since we used it a lot as well.

**Comment by GuySartorelli** [comment]
Further update to this, we aren't looking to add commercial support for this currently. Again, we might look to do it eventually, but for now we're stretched too thin as is. @michalkleiner if you're still keen on taking this on I fully support that.

**Comment by michalkleiner** [comment]
Yeap, I'd be happy to. Not on a full-time basis but as mentioned before, it's a very useful module improving the UX of the CMS when used by CMS devs, so I'm happy to dedicate a bit of time to this.

**Comment by chrispenny** [comment]
Hay team,

Did anyone else end up becoming a maintainer? I have raised a [PR for Silverstripe 5 support](https://github.com/unclecheese/silverstripe-display-logic/pull/152) :)

**Comment by michalkleiner** [comment]
Keen to see what you come up with, @kinglozzer! For the meantime this module definitely has its place.

Yep, @chrispenny, unclecheese shared the reins with me so I can have a look at that.
