### ISSUE TITLE
Dynamically setting the "required" flag

### ISSUE THREAD

**Issue by moniuch** [unclecheese/silverstripe-display-logic#25]
Could we have a feature to make fields dynamically required, based on state of other fields?
I would for example want to enable a TextField depending on whether currently selected dropdown item (its label, not value) contains a phrase. When the text field gets enabled, it also has to be filled in, so it should be made "required".

**Comment by michalkleiner** [comment]
Hello! Thank you for raising the feature request and apologies it hasn't been responded to earlier.

If you can provide a PR, we will consider it. However, the suggested feature is a bit out of scope for the module, so we can't dedicate time to it ourselves.

**Comment by GuySartorelli** [comment]
I'd say validation is definitely out of scope for this module... https://github.com/GuySartorelli/silverstripe-composable-validators has a validator I created specifically for this purpose for people who need it.

**Comment by moniuch** [comment]
Closing the ticket :) I'm no longer a SS user and at that time I might have wrongly identified the correct place to file the request. Thank you.
