### ISSUE TITLE
displayLogicCriteria returning null so onBeforeRender not including assets

### ISSUE THREAD

**Issue by dizzystuff** [unclecheese/silverstripe-display-logic#33]
Hi! Love this mod (and all your mods UncleCheese, let me add another thank you to what's hopefully a long list of grateful SS devs). Just did an install via composer of master into a relatively clean 3.1.8 and found displaylogic js and css not being included. Some poking around shows `$this->displayLogicCriteria` is returning null when checked in `onBeforeRender`, so the assets are not being added via `Requirements::`. I'm not sure if I'm doing something wrong, but my code was a pretty bare bones use of `$field->displayIf('OtherFieldName')->equalTo('value')`. Definitely wasn't a flush issue.

A switch back to tag 1.0.8 and everything was fine. I'd debug further but I'm on a tight deadline today. As always I suppose. If I get the chance later in the week I'll dig around further. Cheers.

**Comment by unclecheese** [comment]
Hi, Luke,

I haven't experienced anything like this in my testing. Can you send me your code?
