### ISSUE TITLE
DisplayLogicWrapper does not work with displayIf in 1.1.0

### ISSUE THREAD

**Issue by brokemeisteratwork** [unclecheese/silverstripe-display-logic#34]
The Attributes in onBeforeRender do not work with DisplayLogicWrapper.
The Template etc. is missing

**Comment by unclecheese** [comment]
Use dev-master. Will be releasing 1.3 once it's tested.

**Comment by dospuntocero** [comment]
hi @unclecheese do you have an ETA for this? i'm just in the middle of a project that needs this feature to show on demand gridfields. thanks for your time

**Comment by unclecheese** [comment]
It's on dev-master

**Comment by michalkleiner** [comment]
Closing this issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5

If your problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using.
