### ISSUE TITLE
UploadField now requires a DisplayLogicWrapper?

### ISSUE THREAD

**Issue by purplespider** [unclecheese/silverstripe-display-logic#35]
In 1.0.8 it used to be possible to use display conditions directly on an ````UploadField````. However, this seemed to break completely in 1.1.0, and in the latest master only seems possible when using a ````DisplayLogicWrapper```` around the ````UploadField````.

Just wanted to check if this was the desired behaviour? As took me a while to work out why it has stopped working, and would be good to have an ````UploadField```` example in the docs. :)

**Comment by purplespider** [comment]
Doh! You do have an UploadField example in the docs!

**Comment by unclecheese** [comment]
It is the desired behaviour. All non-standard form fields will now need wrappers. The only realistic alternative is to override the form field holders, and in finding that just creates way too many conflicts and unexpected outcomes. 

This will all be documented once dev-mater gets tagged to 1.2.

**Comment by purplespider** [comment]
Thanks for confirming, and thanks for your latest add-ons. Permamail and Dropzone will come in extremely useful! :)

**Comment by unclecheese** [comment]
Hey, man. That’s awesome to hear. Hit me up in IRC or email me at unclecheese at leftandmain dotcom if you ever have any further feedback.. always keen to hear. I’m really excited about these two.

aaron_carlino: {
web_developer: “leftandmain.com"
}
