### ISSUE TITLE
DisplayLogic v1.2.1 seems not to work with UploadField

### ISSUE THREAD

**Issue by MarioHofer** [unclecheese/silverstripe-display-logic#39]
I have a couple of fields (eg. DropDown, TextField, etc.) and they all work with DisplayLogic, except UploadField. Here ist my code:

UploadField::create('Visual', _t('Dict.VISUAL', 'Visual'))
	->displayIf('Type')->isEqualTo('image')->end()
	->setFolderName('MainTeasers')

Anything wrong with it? Thanks in advance.

**Comment by unclecheese** [comment]
Use `DisplayLogicWrapper` for nonstandard form fields. See the README.

**Comment by MarioHofer** [comment]
Sorry, didn't know that UploadField is nonstandard. Worked without wrapper in an earlier project I had.

With the wrapper it now works like charm! Thank you so much!
