### ISSUE TITLE
Display logic doesn't seem to work on UploadFields.

### ISSUE THREAD

**Issue by pitchandtone** [unclecheese/silverstripe-display-logic#40]
$uploadField = UploadField::create('Image', 'Image')
			->setAllowedFileCategories('image')
			->setAllowedMaxFileNumber(1)
			->setFolderName('Uploads/images');

		$uploadField->hideUnless('ImageType')->isEqualTo('Single');
		$fields->push($uploadField);

**Comment by unclecheese** [comment]
I believe this is a case where you need `DisplayLogicWrapper`.

https://github.com/unclecheese/silverstripe-display-logic#dealing-with-non-standard-form-fields

**Comment by pitchandtone** [comment]
Yup.
