### ISSUE TITLE
TreeDropdownField doesn't work

### ISSUE THREAD

**Issue by tractorcow** [unclecheese/silverstripe-display-logic#41]
Because it doesn't allow you to set custom attributes within its template.

**Comment by unclecheese** [comment]
That's what `DisplayLogicWrapper` is for, I think.

https://github.com/unclecheese/silverstripe-display-logic#dealing-with-non-standard-form-fields

**Comment by tractorcow** [comment]
Ah, I should read thedocs :) I'll close then heh.
