### ISSUE TITLE
Need nested conditionals example

### ISSUE THREAD

**Issue by hailwood** [unclecheese/silverstripe-display-logic#46]
Hey Cheese,

Can we please get an example of how we would display a field if either of two sets of conditionals are true?

E.g. 

Fields A, B, C, D

Field D should show if
A = 1 AND B = 2
-or-
A = 2 AND C = 2

I thought this should work (and PHP doesn't complain), but the JS only outputs the first part of the conditional (if A = 1 AND B = 2).

``` php
->displayIf('ApplicationType')->isEqualTo('Individual')
->andIf("NZResidentIndividual")->isEqualTo("No")
  ->group()->orIf()
    ->group()
      ->andIf("ApplicationType")->isEqualTo("Joint")
      ->andIf("NZResidentJoint")->isEqualTo("No")
->end()
```

**Comment by michalkleiner** [comment]
I think the [kitchen sink example](https://github.com/unclecheese/silverstripe-display-logic#kitchen-sink-example) covers this now.
