### ISSUE TITLE
Display Logic does not work with Blocks

### ISSUE THREAD

**Issue by namnn96** [unclecheese/silverstripe-display-logic#62]
Hey @unclecheese ,

I am using blocks to manage content and some of the blocks has display logic.

If I edit each block at a time then display logic works but when I want to edit multi block, display logic does not work as expected. Is it a problem regarding version or something that these 2 modules conflict?

Thank you

**Comment by michalkleiner** [comment]
Closing this issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5

If your problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using.
