### ISSUE TITLE
Doesn't seem to work with the DatetimeField

### ISSUE THREAD

**Issue by mooror** [unclecheese/silverstripe-display-logic#67]
I tried using ->displayIf("CheckboxField")->isChecked(); on my Datetime field and it doesn't seem to work. It will hide the field but when I do hit the checkbox it doesn't appear. Here is my code:

```public function getCMSFields() {
    $fields = FieldList::create(TabSet::create('Root'));    
    $defautTokenExpire = $this->addToCurrentDate(array('3'));
    $fields->addFieldsToTab("Root.Main", array(
      ReadonlyField::create("OwnerID.Name","Token Owner"),
      TextField::create("Token","Token"),
      DropdownField::create('StatusID','Status',ApiAccountStatus::get()->map('ID','Name'),2),
      CheckboxField::create("Expires","Does this token expire?"),
      $expiresOnField = DatetimeField::create('ExpiresOn', 'Expires on',$defautTokenExpire),
      $autoRenewField = CheckboxField::create("AutoRenew","Auto renew?")
    ));
    //$expiresOnField->displayIf("Expires")->isChecked();
    $expiresOnField->setConfig('datavalueformat', 'yyyy-MM-dd HH:mm:ss'); // global setting
    $expiresOnField->getDateField()->setConfig('showcalendar', 1); // field-specific setting
    $expiresOnField->setAttribute('placeholder', 'Click to select a date');
    $expiresOnField->setTimeField(TimePickerField::create('ExpiresOn[time]'));
    $autoRenewField->displayIf("Expires")->isChecked();
    return $fields;
  }```

**Comment by unclecheese** [comment]
When in doubt, wrap the field in `DisplayLogicWrapper`. The template overrides only work for common fields.  More info: https://github.com/unclecheese/silverstripe-display-logic#dealing-with-non-standard-form-fields

**Comment by mooror** [comment]
Yeah I read the desciption on that section and it said "you will want to wrap display logic around a form field that does not use the standard FormField template". But when I had checked the DateTimeField in the API Docs it seemed to be a child of FormField. But anyway this code seems to work fine for me:

```
$fields->addFieldToTab("Root.Main", $wrapper = DisplayLogicWrapper::create(
        $expiresOnField = DatetimeField::create('ExpiresOn', 'Expires on',$defautTokenExpire)
      )
    );

$wrapper->displayIf("Expires")->isChecked();
```

Thanks for your help,
Mooror

P.S. Thanks for all the amazing modules you create.

**Comment by unclecheese** [comment]
Thanks for the feedback. Yeah, it could be a number of things. If that form field is attaching behaviours to the DOM that are in conflict with display-logic. Who knows. I think in a future release, the DisplayLogicWrapper will be compulsory, just for consistency. 

```php
DisplayLogicTrigger::create(CheckboxField::create('ShowSomething')),
DisplayLogicTarget::create(TextField::create('SomeTextField'))
   ->displayIf('ShowSomething')
   ->isChecked()
    ->end()
```

or...

```php
DisplayLogicTrigger::create(CheckboxField::create('ShowSomething'))
    ->when('checked')
       ->show('SomeTextField')
       ->hide('SomethingElse')
    ->end(),
DisplayLogicTarget::create(TextField::create('SomeTextField'))
```

**Comment by UndefinedOffset** [comment]
@unclecheese I agree I think that this type of change would solve pretty much every single issue I've ever had with display_logic. It sort of seems like it's a bit redundant but at the same time it solves allot more problems than the extra redundancy is worth. That said I think you'd need to have a compatibility period where it throws deprecation warnings since this is such a breaking change ;). (Ref from #69)

**Comment by unclecheese** [comment]
Well, it would be a major release. Here's to hoping no one is just running `dev-master`. :)

The fact that there are so many edge cases where `DisplayLogicWrapper` is explicitly necessary is troubling to me, and it creates a really bloated API. I agree with you that it feels redundant, but if it's done in the interest of creating a uniform way of using it, I would say it's worth it. It's not as if the `DisplayLogicWrapper` shim comes up once in a blue moon. Any time you need anything other than a text field, it seems to rear its ugly head.

If we wanted maximum backward compatibility, we could simply have `displayIf` return a `DisplayLogicWrapper`. That may solve 90% of the issues.

**Comment by UndefinedOffset** [comment]
I think it does make sense to switch it over to the just be ``DisplayLogicWrapper`` that actually does the display logic stuff. Your compatibility idea would probably solve the backward compatibility issue for sure.

Oh and sorry for the deleted comment ;) GitHub used to not send notifications for closed issues, and I didn't realize this was closed until after I posted so I removed it.
