### ISSUE TITLE
Fatal error: Object::add_extension() - Extension "FormField" is not a subclass of Extension in C:\wamp\www\framework\core\Object.php on line 467

### ISSUE THREAD

**Issue by Josua2012** [unclecheese/silverstripe-display-logic#7]
Hi Aaron!

There is a problem with the latest version 3.1 from github:
https://github.com/silverstripe/silverstripe-cms/tree/3.1
https://github.com/silverstripe/sapphire/tree/3.1

http://127.0.0.1/dev/build?flush=all

Fatal error: Object::add_extension() - Extension "FormField" is not a subclass of Extension in C:\wamp\www\framework\core\Object.php on line 467

<?php
define('DISPLAY_LOGIC_DIR', basename(dirname(**FILE**)));
Object::add_extension("FormField","DisplayLogicFormField");

You must change the way to add an extension:

FormField::add_extension("DisplayLogicFormField");

Regards,
Jose A.

**Comment by michalkleiner** [comment]
Closing this issue since it's outdated and we're now on Silverstripe CMS 4.12.0 and Display Logic 2.0.5

If your problem persists feel free to open a new bug report and provide replication steps and information on what version of Silverstripe CMS and the module you're using.
