### ISSUE TITLE
Display logic is not working with file upload field

### ISSUE THREAD

**Issue by robbyahn** [unclecheese/silverstripe-display-logic#79]
Other components are fine to use. 
However Display logic module is not working with file upload if I use the upload field inside DisplayLogicWrapper. Not able to upload files.

**Comment by unclecheese** [comment]
What do you mean by "not able to upload files?" Does it throw an error?

**Comment by robbyahn** [comment]
Yes, it throws an error. 
When you upload a file, The error message is "Can't control sub class".
I have used has_one relationship.

**Comment by robbyahn** [comment]
This is happened depending on the environment.
