### ISSUE TITLE
Silverstripe 4 support

### ISSUE THREAD

**Issue by adrexia** [unclecheese/silverstripe-display-logic#81]
Some work has been done in this pull request + thread to update to Silverstripe 4, but there were still some issues to resolve and the pull request was eventually closed. 

https://github.com/unclecheese/silverstripe-display-logic/pull/78

**Comment by janneklouman** [comment]
There are now two pull requests for SS4 support.

Perhaps we can discuss here regarding which one to move forward with?

Both come with SS4 compatibility updates, and some code formatting (PSR-2). 

#82 Breaks out `Extensible`/`Injectable`/`Configurable` to `DisplayLogicMain` which is extended by `DisplayLogicCriteri(a|on)`
#83 Adds yarn, adds webpack, adds unit tests, adds onkeyup JS listener.

**Comment by fonsekaean** [comment]
Added two of the main items from the PR #83 on this comment https://github.com/unclecheese/silverstripe-display-logic/pull/82#issuecomment-347736625

**Comment by gorriecoe** [comment]
Is anything happening with these PR's?  #83 seems to work the best and would like to see merged in to master.  I found that #82 intermittently stopped working.

**Comment by muskie9** [comment]
I think a merge to get this 4 compatible would allow easier fixing. Currently it's causing some pain when requiring other modules that are 4 compatible and reference this module as a requirement.

**Comment by christopherdarling** [comment]
Issue could be closed v2 is SS4 compatible - https://github.com/unclecheese/silverstripe-display-logic/pull/82
