### ISSUE TITLE
Non compatible with Rhym/silverstripe-color-field

### ISSUE THREAD

**Issue by digitall-it** [unclecheese/silverstripe-display-logic#84]
On SS3, v1.5 doesn't seem to be compatible with Rhym/silverstripe-color-field. The Display-Logic wrapper seems to see the field as a set of two identical named fields and stops with an user error.

**Comment by digitall-it** [comment]
Issue invalid, problem was unrelated to module. For anyone else sometimes DB Fields get auto added to the page, simply remember to remove them before adding them in the getCMSFields, because the display logic wrapper will complain.

**Comment by michalkleiner** [comment]
You can close the issue yourself @digitall-it.

A rough explanation behind the "sometimes" is that DataObjects use CMS edit forms scaffolding and Pages don't, so for pages, you need to add fields manually and for DOs you need to remove them if you don't want them. Or replace.

**Comment by digitall-it** [comment]
Thank you for the kind words. Is it possible to disable the scaffolding without removing each field separately?

**Comment by michalkleiner** [comment]
Look at DataObject.php file and what `getCMSFields` and `scaffoldFormFields` functions do. It will give you a hint, possibly overriding either of these in your custom DO.
