### ISSUE TITLE
SS 4.1.0 Fatal error: Class 'UncleCheese\DisplayLogic\Wrapper' not found

### ISSUE THREAD

**Issue by vixen1975** [unclecheese/silverstripe-display-logic#88]
This is my first go with Silverstripe 4.0 so my apologies if I have missed something, but I can not get a DisplayLogicWrapper to work, it keeps returning a fatal error. I have added the 'use UncleCheese\DisplayLogic\Wrapper;' in the class and tried both Wrapper::create and DisplayLogicWrapper::create, but neither work.

Also the module did not seem to get picked up until I added a blank _config.php file. 

Is there something I am missing?

**Comment by blueskies79** [comment]
Hi folks! Thanks so much for this module! I ran into "wrapper not found" as well, and noticed it was incorrect in the readme file. Under "Dealing with non-standard form fields", it says: "you can wrap the form field in UncleCheese\DisplayLogic\Wrapper" --> that's the incorrect namespace, as it's missing the \Forms\ bit. So it should be UncleCheese\DisplayLogic\Forms\Wrapper to get it to work.
