### ISSUE TITLE
Doesn't work on silverstripe 4.1

### ISSUE THREAD

**Issue by udarts** [unclecheese/silverstripe-display-logic#89]
Hi there, I have been trying to get this to work on silverstripe 4.1, but I am getting an internal server error when trying to open a tab where that setting is located.

Does this addon work on 4.1 and is there a proper documentation on how to implement it, as I tried the sample code, but that gave me the error.

Cheers,

**Comment by g4b0** [comment]
+1 

The following code:
```php
$owner = DropdownField::create('OwnerID', 'Owner', Customer::get()->sort('Name')->map())
        ->setHasEmptyDefault(true)
        ->displayIf('NotOwnedByZirak')->isChecked()
        ->setDescription('Da popolare solo se il proprietario del device è un cliente');
```
results in the following error: 
```
[Emergency] Uncaught BadMethodCallException: Object->__call(): extra method setDescription is invalid on UncleCheese\DisplayLogic\Criteria
```

**Comment by unclecheese** [comment]
You forgot to call `->end()`

**Comment by g4b0** [comment]
Wow! Faster than light :)

**Comment by christopherdarling** [comment]
@g4b0 @unclecheese  looks like this can be closed
