### ISSUE TITLE
Display logic with SS 4.2 layout issue

### ISSUE THREAD

**Issue by mfendeksilverstripe** [unclecheese/silverstripe-display-logic#95]
DIsplay logic (conditional fields that are displayed only in certain cases) has some layout issues with SilverStripe SS 4.2. The problem is that display logic assumes that element display is "block", but it's actually "flex" in SS4.2.

If conditionally displayed field becomes visible it will have the display set to "block", instead of "flex". This causes the UI to not display the field properly.

Does not affect functionality, just display.

Module version: 2.0.1

**Comment by unclecheese** [comment]
This is resolved in https://github.com/unclecheese/silverstripe-display-logic/commit/845ab12189439422b6dcd1becd20c9d5a94eb558 tagged `2.0.2`
